tag @s add arena
scoreboard players set @s cd1 561
scoreboard players set @s skill 0
scoreboard players set @s skill2 0
clear @s minecraft:carrot_on_a_stick{arena:1}

summon armor_stand ~ ~ ~ {Invulnerable:1b,Marker:1b,Invisible:1b,NoBasePlate:1b,CustomName:"{\"text\":\"arena\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

summon armor_stand ~ ~1 ~ {Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Pose:{LeftArm:[312f,68f,344f],RightArm:[180f,180f,335f]},DisabledSlots:4144959,HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{CustomModelData:8}},{id:"minecraft:shield",Count:1b,tag:{BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}}}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}}}],CustomName:"{\"text\":\"gladiator\"}"}

playsound minecraft:entity.evoker.prepare_wololo master @a ~ ~ ~ 1 1.1
playsound minecraft:entity.evoker.prepare_wololo master @a ~ ~ ~ 1 1
playsound minecraft:entity.evoker.prepare_wololo master @a ~ ~ ~ 1 0.9
playsound minecraft:entity.evoker.prepare_wololo master @a ~ ~ ~ 1 0.8
playsound minecraft:entity.evoker.prepare_wololo master @a ~ ~ ~ 1 0.7

execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~0 ~ ~5 facing entity @s eyes
execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~1 ~ ~5 facing entity @s eyes
execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~2 ~ ~5 facing entity @s eyes
execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~-1 ~ ~5 facing entity @s eyes
execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~-2 ~ ~5 facing entity @s eyes

execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~0 ~ ~-5 facing entity @s eyes
execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~1 ~ ~-5 facing entity @s eyes
execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~2 ~ ~-5 facing entity @s eyes
execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~-1 ~ ~-5 facing entity @s eyes
execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~-2 ~ ~-5 facing entity @s eyes

execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~5 ~ ~0 facing entity @s eyes
execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~5 ~ ~1 facing entity @s eyes
execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~5 ~ ~2 facing entity @s eyes
execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~5 ~ ~-1 facing entity @s eyes
execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~5 ~ ~-2 facing entity @s eyes

execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~-5 ~ ~0 facing entity @s eyes
execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~-5 ~ ~1 facing entity @s eyes
execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~-5 ~ ~2 facing entity @s eyes
execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~-5 ~ ~-1 facing entity @s eyes
execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~-5 ~ ~-2 facing entity @s eyes

execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~4 ~ ~-3 facing entity @s eyes
execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~4 ~ ~3 facing entity @s eyes
execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~3 ~ ~-4 facing entity @s eyes
execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~3 ~ ~4 facing entity @s eyes

execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~-4 ~ ~-3 facing entity @s eyes
execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~-4 ~ ~3 facing entity @s eyes
execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~-3 ~ ~-4 facing entity @s eyes
execute as @e[type=minecraft:armor_stand,name=gladiator,limit=1,distance=..2] run teleport @s ~-3 ~ ~4 facing entity @s eyes

particle dust 0.753 0.753 0.753 2 ~ ~ ~ 3.5 0.5 3.5 0 500 force
particle dust 0.980 0.980 0.980 2 ~ ~ ~ 3.5 0.5 3.5 0 250 force

give @s minecraft:red_stained_glass_pane{display:{Name:"{\"text\":\"Ability on Cooldown\",\"color\":\"red\",\"bold\":true}",Lore:["{\"text\":\"This ability is on cooldown\",\"color\":\"gray\",\"italic\":true}"]},HideFlags:1,Enchantments:[{id:"minecraft:protection",lvl:1s}]} 28

schedule function datapack:pvp/arenaoff 7s