tag @s add hydro
scoreboard players set @s wnadedummy 0

give @s minecraft:trident{Unbreakable:1,display:{Name:"{\"text\":\"Kraken\",\"color\":\"blue\",\"bold\":true}",Lore:["{\"text\":\"Unleash the sea's wroth.\"}"]},AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"Damage",Slot:"mainhand",Amount:4,Operation:0,UUIDMost:77236,UUIDLeast:107715}],Enchantments:[{id:"minecraft:loyalty",lvl:3}],CustomModelData:1,HideFlags:4} 1
replaceitem entity @s weapon.offhand minecraft:trident{display:{Name:"{\"text\":\"Maelstrom\",\"color\":\"blue\",\"bold\":true}",Lore:["{\"text\":\"The tides turn.\"}"]},Enchantments:[{id:"minecraft:riptide",lvl:2}],AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"Damage",Slot:"mainhand",Amount:4,Operation:0,UUIDMost:77236,UUIDLeast:107715},{AttributeName:"generic.attackDamage",Name:"Damage",Slot:"offhand",Amount:4,Operation:0,UUIDMost:39156,UUIDLeast:155810}],Unbreakable:1,CustomModelData:2,HideFlags:4} 1
give @s minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\"Blessing of the Sea\",\"color\":\"gold\",\"bold\":true}",},Unbreakable:1,Enchantments:[{id:"minecraft:power",lvl:1}],rain:1,HideFlags:5,CustomModelData:1} 1
replaceitem entity @s hotbar.2 minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\"Whirlpool Grenade (3 charges)\",\"color\":\"gold\",\"bold\":true}",},Unbreakable:1,Enchantments:[{id:"minecraft:power",lvl:1}],wnade:1,HideFlags:5,CustomModelData:20} 1
replaceitem entity @s armor.head minecraft:player_head{display:{Name:"{\"text\":\"Aquatic God\"}"},SkullOwner:{Id:"c057432c-9e14-431f-8629-ecbc562d4e9c",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWMyODE4ZmIxNjNmZGFhMzE2MjM3MWU3OWQyMThmNDZiM2QxZThkYTYzMmRjYzk1MzJiYjVlY2E4OWRlNDMyIn19fQ=="}]}},AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:20,Operation:0,UUIDLeast:936908,UUIDMost:489496,Slot:"head"}]}
replaceitem entity @s armor.chest minecraft:leather_chestplate{display:{Name:"{\"text\":\"Naga Scalemail\"}",color:4497605},Unbreakable:1b,Enchantments:[{id:"minecraft:depth_strider",lvl:2s}],AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:11,Operation:0,UUIDLeast:177917,UUIDMost:99595,Slot:"chest"}]} 1
replaceitem entity @s armor.feet minecraft:leather_boots{display:{Name:"{\"text\":\"Aqua Fins\",\"color\":\"green\",\"bold\":true}",color:8585203},Unbreakable:1b,Enchantments:[{id:"minecraft:feather_falling",lvl:6s}],AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:1,Operation:0,UUIDLeast:725301,UUIDMost:198518,Slot:"feet"}]} 1