give @s minecraft:iron_sword{display:{Name:'{"text":"Orb of Power","color":"blue","bold":true,"italic":true}',Lore:['{"text":"The purest form of greatness.","color":"dark_purple"}']},HideFlags:5,Unbreakable:1b,Enchantments:[{id:"minecraft:sweeping",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:3,Operation:0,UUIDLeast:386618,UUIDMost:769139,Slot:"mainhand"},{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:3,Operation:0,UUIDLeast:404271,UUIDMost:407151,Slot:"mainhand"}]} 1

replaceitem entity @s weapon.offhand minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\"Arcane Barrage\",\"color\":\"gold\",\"bold\":true}",},Unbreakable:1,Enchantments:[{id:"minecraft:power",lvl:1}],barrageu:1,HideFlags:5,CustomModelData:21} 1

give @s minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\"Orb of Destruction\",\"color\":\"gold\",\"bold\":true}",},Unbreakable:1,Enchantments:[{id:"minecraft:power",lvl:1}],orbd:1,HideFlags:5,CustomModelData:20} 1

replaceitem entity @s armor.head minecraft:player_head{display:{Name:'{"text":"Arcane Hood","color":"green","bold":true,"italic":true}'},AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:20,Operation:0,UUIDLeast:878604,UUIDMost:315367,Slot:"head"}],SkullOwner:{Id:"aebaed94-875d-427a-9d9b-c44390fbd8ba",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGQ4OGZhNzRkYzkyZWUxMDQ0NmVmYjg2YWQ1YzZjOTVhMzk4ZTMxMjU5Y2RlNTIxYWE3MzIyZWY5MmRjMjEzYiJ9fX0="}]}}} 1

replaceitem entity @s armor.chest minecraft:leather_chestplate{display:{Name:'{"text":"Arcane Mantle","color":"green","bold":true,"italic":true}',color:4637757},HideFlags:4,Unbreakable:1b,Enchantments:[{id:"minecraft:blast_protection",lvl:1s},{id:"minecraft:projectile_protection",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:4,Operation:0,UUIDLeast:878604,UUIDMost:315367,Slot:"chest"}]} 1

replaceitem entity @s armor.legs minecraft:leather_leggings{display:{Name:'{"text":"Arcane Kilt","color":"green","bold":true,"italic":true}',color:4637757},HideFlags:5,Unbreakable:1b,Enchantments:[{id:"minecraft:unbreaking",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:4,Operation:0,UUIDLeast:878604,UUIDMost:315367,Slot:"legs"}]} 1

replaceitem entity @s armor.feet minecraft:leather_boots{display:{Name:'{"text":"Arcane Shoes","color":"green","bold":true,"italic":true}',color:4637757},HideFlags:5,Unbreakable:1b,Enchantments:[{id:"minecraft:unbreaking",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:3,Operation:0,UUIDLeast:878604,UUIDMost:315367,Slot:"feet"},{AttributeName:"generic.movementSpeed",Name:"generic.movementSpeed",Amount:0.1,Operation:1,UUIDLeast:241637,UUIDMost:996454,Slot:"feet"}]} 1

tag @s add arc