give @s iron_sword{display:{Name:'{"text":"Realityweave Dagger","color":"blue","bold":true,"italic":false}',Lore:['{"text":"Bend the rules.","color":"gray","italic":true}']},HideFlags:4,Unbreakable:1b,CustomModelData:10,Enchantments:[{id:"minecraft:sharpness",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.attack_damage",Name:"generic.attack_damage",Amount:3,Operation:0,UUID:[I;0,139602,0,187238],Slot:"mainhand"},{AttributeName:"generic.attack_speed",Name:"generic.attack_speed",Amount:3,Operation:0,UUID:[I;0,340661,0,974861],Slot:"mainhand"}]} 1
item replace entity @s weapon.offhand with iron_sword{display:{Name:'{"text":"Realitybreak Greatsword","color":"blue","bold":true,"italic":false}',Lore:['{"text":"Break the rules.","color":"gray","bold":true}']},HideFlags:4,Unbreakable:1b,CustomModelData:11,Enchantments:[{id:"minecraft:sharpness",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.attack_damage",Name:"generic.attack_damage",Amount:7.5,Operation:0,UUID:[I;0,139602,0,187238],Slot:"mainhand"},{AttributeName:"generic.attack_speed",Name:"generic.attack_speed",Amount:-0.87,Operation:1,UUID:[I;0,340661,0,974861],Slot:"mainhand"}]} 1
give @s minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\"Tether Point\",\"color\":\"gold\",\"bold\":true}",},Unbreakable:1,Enchantments:[{id:"minecraft:power",lvl:1}],tpoint:1,HideFlags:5,CustomModelData:14} 1
give @s minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\"Rewind\",\"color\":\"gold\",\"bold\":true}",},Unbreakable:1,Enchantments:[{id:"minecraft:power",lvl:1}],rewind:1,HideFlags:5,CustomModelData:15} 1
item replace entity @s armor.head with player_head{display:{Name:'{"text":"Mirage","color":"green","bold":true}'},AttributeModifiers:[{AttributeName:"generic.max_health",Name:"generic.max_health",Amount:20,Operation:0,UUID:[I;0,251508,0,98871],Slot:"head"}],SkullOwner:{Id:[I;-1517073830,1306280818,-1630125596,290845368],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGJlMTFmY2Y1MmNhNTliMzhlZjY5ZTM4YjgxNzJmZGUzMTA3ZmM3MWI4YjE0M2ZlZjY3NWU3MmY4MDM5ZDYifX19"}],AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:20,Operation:0,UUIDLeast:936908,UUIDMost:489496,Slot:"head"}]}}} 1
item replace entity @s armor.chest with leather_chestplate{display:{Name:'{"text":"Illusory Platemail","color":"green","bold":true}',color:2817677},HideFlags:4,Unbreakable:1b,Enchantments:[{id:"minecraft:projectile_protection",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:2,Operation:0,UUID:[I;0,678630,0,135044],Slot:"chest"}]} 1
item replace entity @s armor.legs with leather_leggings{display:{Name:'{"text":"Illusory Wraps","color":"green","bold":true}',color:2817677},HideFlags:4,Unbreakable:1b,Enchantments:[{id:"minecraft:projectile_protection",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:1,Operation:0,UUID:[I;0,907958,0,878906],Slot:"legs"}]} 1
item replace entity @s armor.feet with leather_boots{display:{Name:'{"text":"Spectre Treads","color":"green","bold":true}',color:2817677},HideFlags:4,Unbreakable:1b,Enchantments:[{id:"minecraft:feather_falling",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:1,Operation:0,UUID:[I;0,615953,0,389628],Slot:"feet"}]} 1

execute as @s run function datapack:pvp/rewindinit