tag @s add trick

give @s iron_sword{display:{Name:'{"text":"Cane of the King\'s Wit","color":"blue","bold":true}',Lore:['{"text":"Violence is a good joke."}']},HideFlags:4,Unbreakable:1b,CustomModelData:2,Enchantments:[{id:"minecraft:sharpness",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.attack_damage",Name:"generic.attack_damage",Amount:3,Operation:0,UUID:[I;0,56830,0,132626],Slot:"mainhand"},{AttributeName:"generic.attack_speed",Name:"generic.attack_speed",Amount:-3,Operation:0,UUID:[I;0,18647,0,140291],Slot:"mainhand"}]} 1
give @s minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\"Poison Trap\",\"color\":\"gold\",\"bold\":true}"},HideFlags:5,Unbreakable:1b,CustomModelData:5,mine:1} 1
give @s minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\"Remove Traps\",\"color\":\"red\",\"bold\":true}"},HideFlags:5,Unbreakable:1b,CustomModelData:6,destroymine:1} 1
item replace entity @s armor.head with player_head{display:{Name:'{"text":"Jester"}'},AttributeModifiers:[{AttributeName:"generic.max_health",Name:"generic.max_health",Amount:20,Operation:0,UUID:[I;0,489496,0,936908],Slot:"head"}],SkullOwner:{Id:[I;780759048,-1431482799,-1743510576,-2015010110],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmIzNDQwYWI5MGE2OTBkNzNkZmEwNjhlYmJiNmM3ZWZhODhlODg5OGUzZDY0NjBlMmMwODg2ZWVhNjU4MzUyZCJ9fX0="}]}}}
item replace entity @s armor.chest with leather_chestplate{display:{Name:'{"text":"Jester\'s Garb"}',color:10890258},HideFlags:4,Unbreakable:1b,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:4,Operation:0,UUID:[I;0,55844,0,163652],Slot:"chest"}]} 1
item replace entity @s armor.legs with leather_leggings{display:{Name:'{"text":"Jester\'s Pants"}',color:15900179},HideFlags:4,Unbreakable:1b,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:4,Operation:0,UUID:[I;0,76997,0,136692],Slot:"legs"}]} 1
item replace entity @s armor.feet with leather_boots{display:{Name:'{"text":"Jester Shoes"}',color:10890258},HideFlags:4,Unbreakable:1b,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:3,Operation:0,UUID:[I;0,46784,0,123220],Slot:"feet"}]} 1
