tag @s add trick

give @s minecraft:iron_sword{display:{Name:"{\"text\":\"Cane of the King's Wit\",\"color\":\"blue\",\"bold\":true}",Lore:["{\"text\":\"Violence is a good joke.\"}"]},HideFlags:4,Unbreakable:1b,CustomModelData:2,Enchantments:[{id:"minecraft:sharpness",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:3,Operation:0,UUIDLeast:132626,UUIDMost:56830,Slot:"mainhand"},{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-3,Operation:0,UUIDLeast:140291,UUIDMost:18647,Slot:"mainhand"}]} 1
give @s minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\"Poison Trap\",\"color\":\"gold\",\"bold\":true}"},HideFlags:5,Unbreakable:1b,CustomModelData:5,mine:1} 1
give @s minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\"Remove Traps\",\"color\":\"red\",\"bold\":true}"},HideFlags:5,Unbreakable:1b,CustomModelData:6,destroymine:1} 1
replaceitem entity @s armor.head minecraft:player_head{display:{Name:"{\"text\":\"Jester\"}"},SkullOwner:{Id:"2e897008-aaad-4e51-9814-23d087e562c2",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmIzNDQwYWI5MGE2OTBkNzNkZmEwNjhlYmJiNmM3ZWZhODhlODg5OGUzZDY0NjBlMmMwODg2ZWVhNjU4MzUyZCJ9fX0="}]}},AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:20,Operation:0,UUIDLeast:936908,UUIDMost:489496,Slot:"head"}]}
replaceitem entity @s armor.chest minecraft:leather_chestplate{display:{Name:"{\"text\":\"Jester's Garb\"}",color:10890258},Unbreakable:1,HideFlags:4,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"chest",Amount:4,Operation:0,UUIDMost:55844,UUIDLeast:163652}]} 1
replaceitem entity @s armor.legs minecraft:leather_leggings{display:{Name:"{\"text\":\"Jester's Pants\"}",color:15900179},Unbreakable:1,HideFlags:4,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"legs",Amount:4,Operation:0,UUIDMost:76997,UUIDLeast:136692}]} 1
replaceitem entity @s armor.feet minecraft:leather_boots{display:{Name:"{\"text\":\"Jester Shoes\"}",color:10890258},Unbreakable:1,HideFlags:4,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"feet",Amount:3,Operation:0,UUIDMost:46784,UUIDLeast:123220}]} 1
