summon minecraft:armor_stand -57 69 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,CustomName:'{"text":"BLOODHUNTER","color":"gold","bold":true}',Tags:["class"]}
summon minecraft:armor_stand -57 68.25 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'[{"text":"Skill: ","color":"aqua","bold":true},{"text":"Sanguine Hunt","color":"white","bold":false}]'}
summon minecraft:armor_stand -57 68 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'{"text":"Gains movement speed and increased jump height, and","color":"white"}'}
summon minecraft:armor_stand -57 67.75 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'{"text":"allows you to steal health when hitting enemies.","color":"white"}'}
summon minecraft:armor_stand -57 67.25 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'[{"text":"Skill: ","color":"aqua","bold":true},{"text":"Blood Rain","color":"white","bold":false}]'}
summon minecraft:armor_stand -57 67 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'{"text":"Summons a cloud of blood above you. Anyone hit by","color":"white"}'}
summon minecraft:armor_stand -57 66.75 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'{"text":"its droplets are blinded and their life leeched.","color":"white"}'}

summon minecraft:item -58 66 -45 {NoGravity:1b,Age:-32768,PickupDelay:32767,Item:{id:"minecraft:carrot_on_a_stick",Count:1b,tag:{CustomModelData:7}},Tags:["class"]}
summon minecraft:item -56 66 -45 {NoGravity:1b,Age:-32768,PickupDelay:32767,Item:{id:"minecraft:carrot_on_a_stick",Count:1b,tag:{CustomModelData:7}},Tags:["class"]}

item replace entity @e[tag=classdummy] weapon.mainhand with minecraft:iron_sword{display:{Name:"{\"text\":\"Lifehunt Scythe\",\"color\":\"blue\",\"bold\":true}",Lore:["{\"text\":\"Blood for the bloodhunter.\"}"]},HideFlags:4,Unbreakable:1b,CustomModelData:3,Enchantments:[{id:"minecraft:sharpness",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-3,Operation:0,UUIDLeast:162912,UUIDMost:23681,Slot:"mainhand"},{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:5.7,Operation:0,UUIDLeast:122511,UUIDMost:67572,Slot:"mainhand"}]} 1
item replace entity @e[tag=classdummy] armor.head with minecraft:player_head{display:{Name:"{\"text\":\"Vampire\"}"},SkullOwner:{Id:[I;-1469047042,-460435777,-1471890276,2041827409],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGQ0NDc1NmUwYjRlY2U4ZDc0NjI5NmEzZDVlMjk3ZTE0MTVmNGJhMTc2NDdmZmUyMjgzODUzODNkMTYxYTkifX19"}]}},AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:20,Operation:0,UUIDLeast:936908,UUIDMost:489496,Slot:"head"}]}
item replace entity @e[tag=classdummy] armor.chest with minecraft:leather_chestplate{display:{Name:"{\"text\":\"Shadow Robe\"}",color:526344},AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"chest",Amount:4,Operation:0,UUIDMost:79228,UUIDLeast:144644}]} 1
item replace entity @e[tag=classdummy] armor.legs with minecraft:leather_leggings{display:{Name:"{\"text\":\"Bloodhunt Legwraps\"}",color:10354688},AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"legs",Amount:1,Operation:0,UUIDMost:62186,UUIDLeast:153191}],HideFlags:4,Unbreakable:1} 1
item replace entity @e[tag=classdummy] armor.feet with minecraft:leather_boots{display:{Name:"{\"text\":\"Bloodhunt Treads\"}",color:10354688},HideFlags:4,Unbreakable:1b,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:1,Operation:0,UUIDLeast:157996,UUIDMost:33408,Slot:"feet"},{AttributeName:"generic.movementSpeed",Name:"generic.movementSpeed",Amount:0.15,Operation:1,UUIDLeast:144311,UUIDMost:32895,Slot:"feet"}]} 1