summon minecraft:armor_stand -57 68 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,CustomName:'{"text":"SILVER GLADIATOR","color":"gold","bold":true}',Tags:["class"]}
summon minecraft:armor_stand -57 67.25 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'[{"text":"Skill: ","color":"aqua","bold":true},{"text":"Gladiator Arena","color":"white","bold":false}]'}
summon minecraft:armor_stand -57 67 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'{"text":"Surrounds you and any nearby enemies with unmoving soldiers. Any enemy","color":"white"}'}
summon minecraft:armor_stand -57 66.75 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'{"text":"that tries to escape is pushed back towards the center and damaged.","color":"white"}'}

summon minecraft:item -57 65.5 -45 {NoGravity:1b,Age:-32768,PickupDelay:32767,Item:{id:"minecraft:carrot_on_a_stick",Count:1b,tag:{CustomModelData:12}},Tags:["class"]}

replaceitem entity @e[tag=classdummy] weapon.mainhand minecraft:iron_sword{display:{Name:"{\"text\":\"Lustrous Spear\",\"color\":\"blue\",\"bold\":true,\"italic\":false}",Lore:["{\"text\":\"The shine on the tip of this spear can be seen yards away\",\"color\":\"gray\",\"italic\":true}"]},Unbreakable:1b,CustomModelData:8,Enchantments:[{id:"minecraft:knockback",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:7,Operation:0,UUIDLeast:801763,UUIDMost:513750,Slot:"mainhand"},{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-0.82,Operation:1,UUIDLeast:961826,UUIDMost:899280,Slot:"mainhand"}]} 1
replaceitem entity @e[tag=classdummy] weapon.offhand minecraft:shield{display:{Name:"{\"text\":\"Titanium Bulwark\",\"color\":\"blue\",\"bold\":true,\"italic\":false}",Lore:["{\"text\":\"Plated in gold alloy\",\"color\":\"gray\",\"italic\":true}"]},HideFlags:32,Unbreakable:1b,Enchantments:[{id:"minecraft:projectile_protection",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.knockbackResistance",Name:"generic.knockbackResistance",Amount:+0.15,Operation:1,UUIDLeast:739037,UUIDMost:938581,Slot:"offhand"}],BlockEntityTag:{Patterns:[{Color:14,Pattern:"cbo"},{Color:14,Pattern:"ss"},{Color:4,Pattern:"mr"},{Color:4,Pattern:"cr"},{Color:14,Pattern:"cbo"},{Color:8,Pattern:"mc"}]}} 1
replaceitem entity @e[tag=classdummy] armor.head minecraft:player_head{display:{Name:"{\"text\":\"Silver Helmet\",\"color\":\"green\",\"bold\":true,\"italic\":false}"},AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:20,Operation:0,UUIDLeast:320205,UUIDMost:326812,Slot:"head"}],SkullOwner:{Id:"55e811d1-9b30-4192-9eac-e4c924186e58",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTAxOThlZWZkMjVlYjI5N2VlYTc2YWUzZmRjMWVlMmExODZiZGM3ZjJhMGIzNjI0YTQzMWI2MjZiYTNjYWYifX19"}]}}} 1
replaceitem entity @e[tag=classdummy] armor.chest minecraft:iron_chestplate{display:{Name:"{\"text\":\"Silver Breasplate\",\"color\":\"green\",\"bold\":true,\"italic\":false}"},HideFlags:4,Unbreakable:1b,Enchantments:[{id:"minecraft:protection",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:+8,Operation:0,UUIDLeast:550659,UUIDMost:800144,Slot:"chest"},{AttributeName:"generic.movementSpeed",Name:"generic.movementSpeed",Amount:-0.16,Operation:1,UUIDLeast:811436,UUIDMost:811544,Slot:"chest"}]} 1
replaceitem entity @e[tag=classdummy] armor.legs minecraft:chainmail_leggings{display:{Name:"{\"text\":\"Warskirt\",\"color\":\"green\",\"bold\":true,\"italic\":false}"},HideFlags:4,Unbreakable:1b,Enchantments:[{id:"minecraft:unbreaking",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:+4,Operation:0,UUIDLeast:520659,UUIDMost:700144,Slot:"legs"}]} 1
replaceitem entity @e[tag=classdummy] armor.feet minecraft:iron_boots{display:{Name:"{\"text\":\"Gladiator Brogan\",\"color\":\"green\",\"bold\":true,\"italic\":false}"},HideFlags:4,Unbreakable:1b,Enchantments:[{id:"minecraft:feather_falling",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:+2,Operation:0,UUIDLeast:559659,UUIDMost:800284,Slot:"feet"},{AttributeName:"generic.knockbackResistance",Name:"generic.knockbackResistance",Amount:0.70,Operation:1,UUIDLeast:513288,UUIDMost:97416,Slot:"feet"}]} 1