summon minecraft:armor_stand -57 68 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,CustomName:'{"text":"CYBERION SOLDIER","color":"gold","bold":true}',Tags:["class"]}
summon minecraft:armor_stand -57 67.25 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'[{"text":"Skill: ","color":"aqua","bold":true},{"text":"Ion Blast","color":"white","bold":false}]'}
summon minecraft:armor_stand -57 67 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'{"text":"Fires a small blast of energy 6 blocks away, dealing damage and","color":"white"}'}
summon minecraft:armor_stand -57 66.75 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'{"text":"knockback. Aim downwards to propel yourself upwards.","color":"white"}'}

summon minecraft:item -57 65.5 -45 {NoGravity:1b,Age:-32768,PickupDelay:32767,Item:{id:"minecraft:carrot_on_a_stick",Count:1b,tag:{CustomModelData:8}},Tags:["class"]}

item replace entity @e[tag=classdummy] weapon.mainhand with minecraft:iron_sword{display:{Name:"{\"text\":\"Ion Fist\",\"color\":\"blue\",\"bold\":true,\"italic\":false}",Lore:["{\"text\":\"Advanced piston mechanisms are all over the fist.\",\"color\":\"gray\"}"]},Unbreakable:1b,CustomModelData:4,Enchantments:[{id:"minecraft:knockback",lvl:2s}],AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:5.8,Operation:0,UUIDLeast:898457,UUIDMost:727849,Slot:"mainhand"},{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-3.5,Operation:0,UUIDLeast:258177,UUIDMost:355981,Slot:"mainhand"}]} 1
item replace entity @e[tag=classdummy] weapon.offhand with minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\"Ion Blast\",\"color\":\"gold\",\"bold\":true}",},Unbreakable:1,Enchantments:[{id:"minecraft:power",lvl:1}],ionblast:1,HideFlags:5,CustomModelData:8} 1
item replace entity @e[tag=classdummy] armor.head with minecraft:player_head{display:{Name:"{\"text\":\"Cyberhead\",\"color\":\"green\",\"bold\":true,\"italic\":false}",Lore:["{\"text\":\"Analyzes 100% of incoming projectiles \",\"color\":\"gray\",\"italic\":true}","{\"text\":\"with 0% success rate.\",\"color\":\"gray\",\"italic\":true}"]},SkullOwner:{Id:[I;-1925825735,286674216,-1522073039,-1856057337],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmQzNzI4NTc5MzEzMWVkNzU1ZjFiMDA5OGYyOWRkNDEzZDY3NjU2YjYyMDg3Mjg5MzU0OTJiNDliMWQwZDRiYSJ9fX0="}]}},AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:20,Operation:0,UUIDLeast:936908,UUIDMost:489496,Slot:"head"}]} 1
item replace entity @e[tag=classdummy] armor.chest with minecraft:leather_chestplate{display:{Name:"{\"text\":\"Cybernetic Plate\",\"color\":\"green\",\"bold\":true}",color:201044},HideFlags:4,Unbreakable:1b,Enchantments:[{id:"minecraft:blast_protection",lvl:1s},{id:"minecraft:projectile_protection",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:4,Operation:0,UUIDLeast:212113,UUIDMost:955820,Slot:"chest"},{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:4,Operation:0,UUIDLeast:937010,UUIDMost:569112,Slot:"chest"}]} 1
item replace entity @e[tag=classdummy] armor.legs with minecraft:leather_leggings{display:{Name:"{\"text\":\"Cybernetic Legs\",\"color\":\"green\",\"bold\":true}",color:878335},HideFlags:4,Unbreakable:1b,AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"generic.movementSpeed",Amount:0.14,Operation:1,UUIDLeast:232113,UUIDMost:959820,Slot:"legs"}]} 1
item replace entity @e[tag=classdummy] armor.feet with minecraft:leather_boots{display:{Name:"{\"text\":\"Cybernetic Stompers\",\"color\":\"green\",\"bold\":true}",color:201044},HideFlags:4,Unbreakable:1b,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:8,Operation:0,UUIDLeast:232113,UUIDMost:959820,Slot:"feet"}]} 1