summon minecraft:armor_stand -57 69 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,CustomName:'{"text":"DUSTSTRIDER","color":"gold","bold":true}',Tags:["class"]}
summon minecraft:armor_stand -57 68.25 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'[{"text":"Skill: ","color":"aqua","bold":true},{"text":"Tornado","color":"white","bold":false}]'}
summon minecraft:armor_stand -57 68 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'{"text":"Summons a tornado in a straight line, lifting up","color":"white"}'}
summon minecraft:armor_stand -57 67.75 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'{"text":"and damaging enemies in its path.","color":"white"}'}
summon minecraft:armor_stand -57 67.25 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'[{"text":"Skill: ","color":"aqua","bold":true},{"text":"Windwrath","color":"white","bold":false}]'}
summon minecraft:armor_stand -57 67 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'{"text":"Pushes back nearby enemies into the air,","color":"white"}'}
summon minecraft:armor_stand -57 66.75 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'{"text":"dealing a moderate amount of damage.","color":"white"}'}

summon minecraft:item -58 66 -45 {NoGravity:1b,Age:-32768,PickupDelay:32767,Item:{id:"minecraft:carrot_on_a_stick",Count:1b,tag:{CustomModelData:4}},Tags:["class"]}
summon minecraft:item -56 66 -45 {NoGravity:1b,Age:-32768,PickupDelay:32767,Item:{id:"minecraft:carrot_on_a_stick",Count:1b,tag:{CustomModelData:5}},Tags:["class"]}

item replace entity @e[tag=classdummy] weapon.mainhand with minecraft:iron_sword{Unbreakable:1,display:{Name:"{\"text\":\"Windslicer\",\"color\":\"blue\",\"bold\":true}",Lore:["{\"text\":\"Face the wind. \"}"]},AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Slot:"mainhand",Amount:3,Operation:0,UUIDMost:54263,UUIDLeast:110168},{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Slot:"mainhand",Amount:1,Operation:0,UUIDMost:65284,UUIDLeast:143703}],HideFlags:4,Enchantments:[{id:"minecraft:sweeping",lvl:3}],CustomModelData:1} 1
item replace entity @e[tag=classdummy] armor.head with minecraft:player_head{display:{Name:"{\"text\":\"Wanderer's Hood\"}"},SkullOwner:{Id:[I;318746246,-579384725,-1563886208,1724453174],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZThjOTgyMDRlZGRmMGY5MzM3NTExYzk0Y2Q0YzBiMzRmZjE5YWQyODUyOTZkOWE4ZDVlMzA3Y2NjZDgyZTIzNiJ9fX0="}]}},AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:20,Operation:0,UUIDLeast:936908,UUIDMost:489496,Slot:"head"}]}
item replace entity @e[tag=classdummy] armor.chest with minecraft:leather_chestplate{Unbreakable:1,display:{Name:"{\"text\":\"Wanderer's Mantle\"}",color:16179128},AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Slot:"chest",Amount:2,Operation:0,UUIDMost:29790,UUIDLeast:133101},{AttributeName:"generic.armor",Name:"generic.armor",Slot:"chest",Amount:5,Operation:0,UUIDMost:83125,UUIDLeast:152924}],HideFlags:4} 1
item replace entity @e[tag=classdummy] armor.legs with minecraft:leather_leggings{Unbreakable:1,display:{Name:"{\"text\":\"Wanderer's Britches\"}",color:16179128},AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"legs",Amount:4,Operation:0,UUIDMost:36134,UUIDLeast:146912},{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Slot:"legs",Amount:2,Operation:0,UUIDMost:24632,UUIDLeast:140551}],HideFlags:4} 1
item replace entity @e[tag=classdummy] armor.feet with minecraft:leather_boots{Unbreakable:1,display:{Name:"{\"text\":\"Wanderer's Sandals\"}",color:16179128},AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"feet",Amount:2,Operation:0,UUIDMost:15178,UUIDLeast:138633}],HideFlags:4,Enchantments:[{id:"minecraft:feather_falling",lvl:1}]} 1
