summon minecraft:armor_stand -57 69 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,CustomName:'{"text":"EMPEROR","color":"gold","bold":true}',Tags:["class"]}
summon minecraft:armor_stand -57 68.25 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'[{"text":"Skill: ","color":"aqua","bold":true},{"text":"Summon Soldier","color":"white","bold":false}]'}
summon minecraft:armor_stand -57 68 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'{"text":"Creates an undead soldier that can be controlled by","color":"white"}'}
summon minecraft:armor_stand -57 67.75 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'{"text":"right-clicking with your weapon, attacking enemies nearby it. Has 2 charges.","color":"white"}'}
summon minecraft:armor_stand -57 67.25 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'[{"text":"Skill: ","color":"aqua","bold":true},{"text":"Conquer","color":"white","bold":false}]'}
summon minecraft:armor_stand -57 67 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'{"text":"Moves all summoned soldiers towards","color":"white"}'}
summon minecraft:armor_stand -57 66.75 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'{"text":"the target position.","color":"white"}'}

summon minecraft:item -58 66 -45 {NoGravity:1b,Age:-32768,PickupDelay:32767,Item:{id:"minecraft:carrot_on_a_stick",Count:1b,tag:{CustomModelData:4}},Tags:["class"]}
summon minecraft:item -56 66 -45 {NoGravity:1b,Age:-32768,PickupDelay:32767,Item:{id:"minecraft:carrot_on_a_stick",Count:1b,tag:{CustomModelData:5}},Tags:["class"]}

replaceitem entity @e[tag=classdummy] weapon.mainhand minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\"Hand of the Empire\",\"color\":\"blue\",\"bold\":true}",Lore:["{\"text\":\"Bow down.\"}"]},HideFlags:4,Unbreakable:1b,command:1,Enchantments:[{id:"minecraft:knockback",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:4,Operation:0,UUIDLeast:628412,UUIDMost:550229,Slot:"mainhand"},{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-1,Operation:0,UUIDLeast:233522,UUIDMost:584007,Slot:"mainhand"}]} 1
replaceitem entity @e[tag=classdummy] armor.head minecraft:player_head{display:{Name:"{\"text\":\"Ruler of the Damned\",\"color\":\"green\",\"bold\":true}"},SkullOwner:{Id:"724617c2-8c2f-43b6-80a1-03718847bab0",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWJlY2RmOTc0N2JjZDcxZTBkZmU3N2E1NmMyMGRjOTk1ODNmMjQ1ZTQ2OWM4M2Y4NGJkMTk1ZWM2ZTJkM2VlMiJ9fX0="}]}},AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:20,Operation:0,UUIDLeast:936908,UUIDMost:489496,Slot:"head"}]} 1
replaceitem entity @e[tag=classdummy] armor.chest minecraft:golden_chestplate{display:{Name:"{\"text\":\"Essence Cuirass\",\"color\":\"green\",\"bold\":true}"},HideFlags:4,Unbreakable:1b,Enchantments:[{id:"minecraft:projectile_protection",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:9,Operation:0,UUIDLeast:247724,UUIDMost:656571,Slot:"chest"}]} 1
replaceitem entity @e[tag=classdummy] armor.legs minecraft:leather_leggings{display:{Name:"{\"text\":\"Soul Greaves\",\"color\":\"green\",\"bold\":true}",color:2829099},HideFlags:4,Unbreakable:1b,Enchantments:[{id:"minecraft:protection",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:4,Operation:0,UUIDLeast:939141,UUIDMost:191749,Slot:"legs"},{AttributeName:"generic.armor",Name:"generic.armor",Amount:4,Operation:0,UUIDLeast:859750,UUIDMost:5081,Slot:"legs"}]} 1
replaceitem entity @e[tag=classdummy] armor.feet minecraft:leather_boots{display:{Name:"{\"text\":\"Soul Walkers\",\"color\":\"green\",\"bold\":true}",color:3891811},HideFlags:4,Unbreakable:1b,Enchantments:[{id:"minecraft:thorns",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:4,Operation:0,UUIDLeast:217948,UUIDMost:187160,Slot:"feet"}]} 1
tag @e[tag=classdummy] add emp
