summon minecraft:armor_stand -57 69 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,CustomName:'{"text":"ARCANIST","color":"gold","bold":true}',Tags:["class"]}
summon minecraft:armor_stand -57 68.25 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'[{"text":"Skill: ","color":"aqua","bold":true},{"text":"Arcane Barrage","color":"white","bold":false}]'}
summon minecraft:armor_stand -57 68 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'{"text":"Creates 4 projectiles in the air that home towards","color":"white"}'}
summon minecraft:armor_stand -57 67.75 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'{"text":"nearby enemies, slowing and damaging them.","color":"white"}'}
summon minecraft:armor_stand -57 67.25 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'[{"text":"Skill: ","color":"aqua","bold":true},{"text":"Orb of Destruction","color":"white","bold":false}]'}
summon minecraft:armor_stand -57 67 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'{"text":"Summons an orb that travels slowly forward, firing bolts of","color":"white"}'}
summon minecraft:armor_stand -57 66.75 -45 {CustomNameVisible:1b,NoGravity:1b,Invulnerable:1b,Marker:1b,Invisible:1b,Tags:["class"],CustomName:'{"text":"energy periodically at nearby targets.","color":"white"}'}

summon minecraft:item -58 66 -45 {NoGravity:1b,Age:-32768,PickupDelay:32767,Item:{id:"minecraft:carrot_on_a_stick",Count:1b,tag:{CustomModelData:21}},Tags:["class"]}
summon minecraft:item -56 66 -45 {NoGravity:1b,Age:-32768,PickupDelay:32767,Item:{id:"minecraft:carrot_on_a_stick",Count:1b,tag:{CustomModelData:20}},Tags:["class"]}

item replace entity @e[tag=classdummy] weapon.mainhand with minecraft:iron_sword{display:{Name:'{"text":"Orb of Power","color":"blue","bold":true,"italic":true}',Lore:['{"text":"The purest form of greatness.","color":"dark_purple"}']},HideFlags:5,Unbreakable:1b,Enchantments:[{id:"minecraft:sweeping",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:3,Operation:0,UUIDLeast:386618,UUIDMost:769139,Slot:"mainhand"},{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:3,Operation:0,UUIDLeast:404271,UUIDMost:407151,Slot:"mainhand"}]} 1

item replace entity @e[tag=classdummy] weapon.offhand with minecraft:carrot_on_a_stick{display:{Name:"{\"text\":\"Arcane Barrage\",\"color\":\"gold\",\"bold\":true}",},Unbreakable:1,Enchantments:[{id:"minecraft:power",lvl:1}],barrageu:1,HideFlags:5,CustomModelData:21} 1

item replace entity @e[tag=classdummy] armor.head with minecraft:player_head{display:{Name:'{"text":"Arcane Hood","color":"green","bold":true,"italic":true}'},AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:20,Operation:0,UUIDLeast:878604,UUIDMost:315367,Slot:"head"}],SkullOwner:{Id:[I;-1363481196,-2023931270,-1650736061,-1862543174],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGQ4OGZhNzRkYzkyZWUxMDQ0NmVmYjg2YWQ1YzZjOTVhMzk4ZTMxMjU5Y2RlNTIxYWE3MzIyZWY5MmRjMjEzYiJ9fX0="}]}}} 1

item replace entity @e[tag=classdummy] armor.chest with minecraft:leather_chestplate{display:{Name:'{"text":"Arcane Mantle","color":"green","bold":true,"italic":true}',color:4637757},HideFlags:4,Unbreakable:1b,Enchantments:[{id:"minecraft:blast_protection",lvl:1s},{id:"minecraft:projectile_protection",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:4,Operation:0,UUIDLeast:878604,UUIDMost:315367,Slot:"chest"}]} 1

item replace entity @e[tag=classdummy] armor.legs with minecraft:leather_leggings{display:{Name:'{"text":"Arcane Kilt","color":"green","bold":true,"italic":true}',color:4637757},HideFlags:5,Unbreakable:1b,Enchantments:[{id:"minecraft:unbreaking",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:4,Operation:0,UUIDLeast:878604,UUIDMost:315367,Slot:"legs"}]} 1

item replace entity @e[tag=classdummy] armor.feet with minecraft:leather_boots{display:{Name:'{"text":"Arcane Shoes","color":"green","bold":true,"italic":true}',color:4637757},HideFlags:5,Unbreakable:1b,Enchantments:[{id:"minecraft:unbreaking",lvl:1s}],AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:3,Operation:0,UUIDLeast:878604,UUIDMost:315367,Slot:"feet"},{AttributeName:"generic.movementSpeed",Name:"generic.movementSpeed",Amount:0.1,Operation:1,UUIDLeast:241637,UUIDMost:996454,Slot:"feet"}]} 1