scoreboard players operation @s auCamDummy = CurrentlyCamming auCamDummy
scoreboard players add @s auCamDummy 1
tag @s add aucammingly
#summon minecraft:armor_stand ~ ~-1 ~ {Marker:1b,Invisible:1b,Tags:["auCamDummy","auCamDummying"]}
execute as @s[team=au_red] at @s run summon minecraft:armor_stand ~ ~1 ~ {NoGravity:0b,Silent:1b,Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Tags:["auCamDummy","auCamDummying"],DisabledSlots:4144959,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:16711680}}},{}]}
execute as @s[team=au_blue] at @s run summon minecraft:armor_stand ~ ~1 ~ {NoGravity:0b,Silent:1b,Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Tags:["auCamDummy","auCamDummying"],DisabledSlots:4144959,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:255}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:255}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:255}}},{}]}
execute as @s[team=au_yellow] at @s run summon minecraft:armor_stand ~ ~1 ~ {NoGravity:0b,Silent:1b,Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Tags:["auCamDummy","auCamDummying"],DisabledSlots:4144959,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:16776960}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:16776960}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:16776960}}},{}]}
execute as @s[team=au_green] at @s run summon minecraft:armor_stand ~ ~1 ~ {NoGravity:0b,Silent:1b,Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Tags:["auCamDummy","auCamDummying"],DisabledSlots:4144959,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:29440}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:29440}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:29440}}},{}]}
execute as @s[team=au_white] at @s run summon minecraft:armor_stand ~ ~1 ~ {NoGravity:0b,Silent:1b,Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Tags:["auCamDummy","auCamDummying"],DisabledSlots:4144959,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:16777215}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:16777215}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:16777215}}},{}]}
execute as @s[team=au_black] at @s run summon minecraft:armor_stand ~ ~1 ~ {NoGravity:0b,Silent:1b,Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Tags:["auCamDummy","auCamDummying"],DisabledSlots:4144959,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:0}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:0}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:0}}},{}]}
execute as @s[team=au_pink] at @s run summon minecraft:armor_stand ~ ~1 ~ {NoGravity:0b,Silent:1b,Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Tags:["auCamDummy","auCamDummying"],DisabledSlots:4144959,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:16711927}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:16711927}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:16711927}}},{}]}
execute as @s[team=au_purple] at @s run summon minecraft:armor_stand ~ ~1 ~ {NoGravity:0b,Silent:1b,Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Tags:["auCamDummy","auCamDummying"],DisabledSlots:4144959,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:8782015}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:8782015}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:8782015}}},{}]}
execute as @s[team=au_cyan] at @s run summon minecraft:armor_stand ~ ~1 ~ {NoGravity:0b,Silent:1b,Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Tags:["auCamDummy","auCamDummying"],DisabledSlots:4144959,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:65535}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:65535}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:65535}}},{}]}
execute as @s[team=au_orange] at @s run summon minecraft:armor_stand ~ ~1 ~ {NoGravity:0b,Silent:1b,Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Tags:["auCamDummy","auCamDummying"],DisabledSlots:4144959,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:16753920}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:16753920}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:16753920}}},{}]}
execute as @s[team=au_gray] at @s run summon minecraft:armor_stand ~ ~1 ~ {NoGravity:0b,Silent:1b,Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Tags:["auCamDummy","auCamDummying"],DisabledSlots:4144959,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:13882323}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:13882323}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:13882323}}},{}]}
execute as @s[team=au_lime] at @s run summon minecraft:armor_stand ~ ~1 ~ {NoGravity:0b,Silent:1b,Invulnerable:1b,ShowArms:1b,NoBasePlate:1b,Tags:["auCamDummy","auCamDummying"],DisabledSlots:4144959,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:65280}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:65280}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:65280}}},{}]}
tp @e[tag=auCamDummy,sort=nearest,limit=1] @s
loot replace entity @e[tag=auCamDummy,sort=nearest,limit=1] armor.head loot datapack:head
data modify block 198 193 -282 Text1 set from entity @e[tag=auCamDummy,sort=nearest,limit=1] ArmorItems[3].tag.SkullOwner.Name

scoreboard players operation @e[tag=auCamDummy,sort=nearest,limit=1] auCamDummy = @s auCamDummy
execute as @s[tag=crewmate] at @s run tag @e[tag=auCamDummy,sort=nearest,limit=1] add crewmate
execute as @s[tag=impostor] at @s run tag @e[tag=auCamDummy,sort=nearest,limit=1] add impostor
tag @e[tag=auCamDummy,sort=nearest,limit=1] remove auCamDummy

tellraw @s {"text":"Security Camera Controls:","bold":true,"color":"gold"}
tellraw @s [""]
tellraw @s {"text":"CAM1 - Reactor/Security Hall","color":"aqua","clickEvent":{"action":"run_command","value":"/execute if score @s auCamming matches 1.. run scoreboard players set @s auCamming 1"}}
tellraw @s {"text":"CAM2 - Medybay Hall","color":"aqua","clickEvent":{"action":"run_command","value":"/execute if score @s auCamming matches 1.. run scoreboard players set @s auCamming 2"}}
tellraw @s {"text":"CAM3 - Navigation Hall","color":"aqua","clickEvent":{"action":"run_command","value":"/execute if score @s auCamming matches 1.. run scoreboard players set @s auCamming 3"}}
tellraw @s {"text":"CAM4 - Admin Hall","color":"aqua","clickEvent":{"action":"run_command","value":"/execute if score @s auCamming matches 1.. run scoreboard players set @s auCamming 4"}}
tellraw @s [""]
tellraw @s {"text":"     Exit Cameras","color":"dark_green","clickEvent":{"action":"run_command","value":"/execute if score @s auCamming matches 1.. run function datapack:amongus/leavecamskeld"}}

scoreboard players set @s auCamming 1