execute as @s at @s if entity @e[tag=emeeting,limit=1,sort=nearest,distance=..3] if score emeeting audummy matches 1.. if score oxygencheck audummy matches 2 if score reactorcheck audummy matches 1 if score oxygencheckm audummy matches 2 if score reactorcheckm audummy matches 1 if score seismiccheck audummy matches 1 if score lightscheck audummy matches 5 if score lightscheckp audummy matches 5 if score lightscheckm audummy matches 5 if score CommunicationsDisabled disabledcomms matches 50 run title @s actionbar ["",{"text":"Emergency Meeting ready in ","color":"dark_green"},{"score":{"name":"emeeting","objective":"audummy"},"color":"white"},{"text":" seconds.","color":"dark_green"}]

execute as @s at @s if entity @e[tag=emeeting,limit=1,sort=nearest,distance=..3] unless score oxygencheck audummy matches 2 run title @s actionbar ["",{"text":"You cannot start an emergency meeting during a crisis!","color":"red"}]
execute as @s at @s if entity @e[tag=emeeting,limit=1,sort=nearest,distance=..3] if score reactorcheck audummy matches 0 run title @s actionbar ["",{"text":"You cannot start an emergency meeting during a crisis!","color":"red"}]
execute as @s at @s if entity @e[tag=emeeting,limit=1,sort=nearest,distance=..3] unless score oxygencheckm audummy matches 2 run title @s actionbar ["",{"text":"You cannot start an emergency meeting during a crisis!","color":"red"}]
execute as @s at @s if entity @e[tag=emeeting,limit=1,sort=nearest,distance=..3] if score reactorcheckm audummy matches 0 run title @s actionbar ["",{"text":"You cannot start an emergency meeting during a crisis!","color":"red"}]
execute as @s at @s if entity @e[tag=emeeting,limit=1,sort=nearest,distance=..3] if score seismiccheck audummy matches 0 run title @s actionbar ["",{"text":"You cannot start an emergency meeting during a crisis!","color":"red"}]
execute as @s at @s if entity @e[tag=emeeting,limit=1,sort=nearest,distance=..3] if score lightscheck audummy matches 0 run title @s actionbar ["",{"text":"You cannot start an emergency meeting during a blackout!","color":"red"}]
execute as @s at @s if entity @e[tag=emeeting,limit=1,sort=nearest,distance=..3] if score lightscheckp audummy matches 0 run title @s actionbar ["",{"text":"You cannot start an emergency meeting during a blackout!","color":"red"}]
execute as @s at @s if entity @e[tag=emeeting,limit=1,sort=nearest,distance=..3] if score lightscheckm audummy matches 0 run title @s actionbar ["",{"text":"You cannot start an emergency meeting during a blackout!","color":"red"}]
execute as @s at @s if entity @e[tag=emeeting,limit=1,sort=nearest,distance=..3] unless score CommunicationsDisabled disabledcomms matches 50 run title @s actionbar ["",{"text":"You cannot start an emergency meeting while communications are disabled!","color":"red"}]
execute as @s at @s if entity @e[tag=emeeting,limit=1,sort=nearest,distance=..3] if score emeeting audummy matches 0 if score oxygencheck audummy matches 2 if score reactorcheck audummy matches 1 if score lightscheck audummy matches 5 if score CommunicationsDisabled disabledcomms matches 50 run title @s actionbar ["",{"text":"Emergency Meeting ready!","color":"dark_green"}]

execute as @s at @s if entity @e[tag=auCamCenter,type=armor_stand,limit=1,sort=nearest,distance=..2] unless score CommunicationsDisabled disabledcomms matches 50 run title @s actionbar ["",{"text":"Cannot access Security Cameras while communications are disabled!","color":"dark_red"}]
execute as @s at @s if entity @e[tag=auCamCenter,type=armor_stand,limit=1,sort=nearest,distance=..2] if score CommunicationsDisabled disabledcomms matches 50 run title @s actionbar ["",{"text":"Access Security Cameras","color":"light_purple"}]

execute as @s at @s if entity @e[tag=auadmin,type=armor_stand,limit=1,sort=nearest,distance=..2.5] unless score CommunicationsDisabled disabledcomms matches 50 run title @s actionbar ["",{"text":"Cannot access Amin Log while communications are disabled!","color":"dark_red"}]
execute as @s at @s if entity @e[tag=auadmin,type=armor_stand,limit=1,sort=nearest,distance=..2.5] if score CommunicationsDisabled disabledcomms matches 50 run title @s actionbar ["",{"text":"Access Admin Log","color":"light_purple"}]

execute as @s at @s if entity @e[tag=audpolus1a,limit=1,sort=nearest,distance=..2.3] if score audpolus1a audummy matches 12 if score audpolus1b audummy matches 12 run title @s actionbar {"text":"Open decontamination room","color":"green"}
execute as @s at @s if entity @e[tag=audpolus1b,limit=1,sort=nearest,distance=..2.3] if score audpolus1a audummy matches 12 if score audpolus1b audummy matches 12 run title @s actionbar {"text":"Open decontamination room","color":"green"}
execute as @s at @s if entity @e[tag=audpolus1ai,limit=1,sort=nearest,distance=..2.3] if score audpolus1a audummy matches 12 if score audpolus1b audummy matches 12 run title @s actionbar {"text":"Exit decontamination room","color":"green"}
execute as @s at @s if entity @e[tag=audpolus1bi,limit=1,sort=nearest,distance=..2.3] if score audpolus1a audummy matches 12 if score audpolus1b audummy matches 12 run title @s actionbar {"text":"Exit decontamination room","color":"green"}
execute as @s at @s if entity @e[tag=audpolus1a,limit=1,sort=nearest,distance=..2.3] unless score audpolus1b audummy matches 12 run title @s actionbar {"text":"Decontamination room currently in use. Please wait.","color":"yellow"}
execute as @s at @s if entity @e[tag=audpolus1b,limit=1,sort=nearest,distance=..2.3] unless score audpolus1a audummy matches 12 run title @s actionbar {"text":"Decontamination room currently in use. Please wait.","color":"yellow"}
execute as @s at @s if entity @e[tag=audpolus1b,limit=1,sort=nearest,distance=..2.3] unless score audpolus1b audummy matches 12 run title @s actionbar {"text":"Decontamination room currently in use. Please wait.","color":"yellow"}
execute as @s at @s if entity @e[tag=audpolus1a,limit=1,sort=nearest,distance=..2.3] unless score audpolus1a audummy matches 12 run title @s actionbar {"text":"Decontamination room currently in use. Please wait.","color":"yellow"}

execute as @s at @s if entity @e[tag=audpolus2a,limit=1,sort=nearest,distance=..2.3] if score audpolus2a audummy matches 12 if score audpolus2b audummy matches 12 run title @s actionbar {"text":"Open decontamination room","color":"green"}
execute as @s at @s if entity @e[tag=audpolus2b,limit=1,sort=nearest,distance=..2.3] if score audpolus2a audummy matches 12 if score audpolus2b audummy matches 12 run title @s actionbar {"text":"Open decontamination room","color":"green"}
execute as @s at @s if entity @e[tag=audpolus2ai,limit=1,sort=nearest,distance=..2.3] if score audpolus2a audummy matches 12 if score audpolus2b audummy matches 12 run title @s actionbar {"text":"Exit decontamination room","color":"green"}
execute as @s at @s if entity @e[tag=audpolus2bi,limit=1,sort=nearest,distance=..2.3] if score audpolus2a audummy matches 12 if score audpolus2b audummy matches 12 run title @s actionbar {"text":"Exit decontamination room","color":"green"}
execute as @s at @s if entity @e[tag=audpolus2a,limit=1,sort=nearest,distance=..2.3] unless score audpolus2b audummy matches 12 run title @s actionbar {"text":"Decontamination room currently in use. Please wait.","color":"yellow"}
execute as @s at @s if entity @e[tag=audpolus2b,limit=1,sort=nearest,distance=..2.3] unless score audpolus2a audummy matches 12 run title @s actionbar {"text":"Decontamination room currently in use. Please wait.","color":"yellow"}
execute as @s at @s if entity @e[tag=audpolus2b,limit=1,sort=nearest,distance=..2.3] unless score audpolus2b audummy matches 12 run title @s actionbar {"text":"Decontamination room currently in use. Please wait.","color":"yellow"}
execute as @s at @s if entity @e[tag=audpolus2a,limit=1,sort=nearest,distance=..2.3] unless score audpolus2a audummy matches 12 run title @s actionbar {"text":"Decontamination room currently in use. Please wait.","color":"yellow"}

execute as @s at @s if entity @e[tag=audmira1a,limit=1,sort=nearest,distance=..2.3] if score audmira1a audummy matches 12 if score audmira1b audummy matches 12 run title @s actionbar {"text":"Open decontamination room","color":"green"}
execute as @s at @s if entity @e[tag=audmira1b,limit=1,sort=nearest,distance=..2.3] if score audmira1a audummy matches 12 if score audmira1b audummy matches 12 run title @s actionbar {"text":"Open decontamination room","color":"green"}
execute as @s at @s if entity @e[tag=audmira1ai,limit=1,sort=nearest,distance=..2.3] if score audmira1a audummy matches 12 if score audmira1b audummy matches 12 run title @s actionbar {"text":"Exit decontamination room","color":"green"}
execute as @s at @s if entity @e[tag=audmira1bi,limit=1,sort=nearest,distance=..2.3] if score audmira1a audummy matches 12 if score audmira1b audummy matches 12 run title @s actionbar {"text":"Exit decontamination room","color":"green"}
execute as @s at @s if entity @e[tag=audmira1a,limit=1,sort=nearest,distance=..2.3] unless score audmira1b audummy matches 12 run title @s actionbar {"text":"Decontamination room currently in use. Please wait.","color":"yellow"}
execute as @s at @s if entity @e[tag=audmira1b,limit=1,sort=nearest,distance=..2.3] unless score audmira1a audummy matches 12 run title @s actionbar {"text":"Decontamination room currently in use. Please wait.","color":"yellow"}
execute as @s at @s if entity @e[tag=audmira1b,limit=1,sort=nearest,distance=..2.3] unless score audmira1b audummy matches 12 run title @s actionbar {"text":"Decontamination room currently in use. Please wait.","color":"yellow"}
execute as @s at @s if entity @e[tag=audmira1a,limit=1,sort=nearest,distance=..2.3] unless score audmira1a audummy matches 12 run title @s actionbar {"text":"Decontamination room currently in use. Please wait.","color":"yellow"}


execute as @s at @s if score @e[tag=ldoff1,limit=1,sort=nearest,distance=..2.5] audummy matches 0..5 run title @s actionbar ["",{"text":"This door is locked. ","color":"red"},{"score":{"name":"@e[tag=ldoff1,limit=1]","objective":"audummy"},"bold":true,"color":"gold"},{"text":"/5","bold":true,"color":"gold"}]
execute as @s at @s if score @e[tag=ldoff2,limit=1,sort=nearest,distance=..2.5] audummy matches 0..5 run title @s actionbar ["",{"text":"This door is locked. ","color":"red"},{"score":{"name":"@e[tag=ldoff2,limit=1]","objective":"audummy"},"bold":true,"color":"gold"},{"text":"/5","bold":true,"color":"gold"}]
execute as @s at @s if score @e[tag=ldo21,limit=1,sort=nearest,distance=..2.5] audummy matches 0..5 run title @s actionbar ["",{"text":"This door is locked. ","color":"red"},{"score":{"name":"@e[tag=ldo21,limit=1]","objective":"audummy"},"bold":true,"color":"gold"},{"text":"/5","bold":true,"color":"gold"}]
execute as @s at @s if score @e[tag=ldo22,limit=1,sort=nearest,distance=..2.5] audummy matches 0..5 run title @s actionbar ["",{"text":"This door is locked. ","color":"red"},{"score":{"name":"@e[tag=ldo22,limit=1]","objective":"audummy"},"bold":true,"color":"gold"},{"text":"/5","bold":true,"color":"gold"}]
execute as @s at @s if score @e[tag=ldele1,limit=1,sort=nearest,distance=..2.5] audummy matches 0..5 run title @s actionbar ["",{"text":"This door is locked. ","color":"red"},{"score":{"name":"@e[tag=ldele1,limit=1]","objective":"audummy"},"bold":true,"color":"gold"},{"text":"/5","bold":true,"color":"gold"}]
execute as @s at @s if score @e[tag=ldele2,limit=1,sort=nearest,distance=..2.5] audummy matches 0..5 run title @s actionbar ["",{"text":"This door is locked. ","color":"red"},{"score":{"name":"@e[tag=ldele2,limit=1]","objective":"audummy"},"bold":true,"color":"gold"},{"text":"/5","bold":true,"color":"gold"}]
execute as @s at @s if score @e[tag=ldele3,limit=1,sort=nearest,distance=..2.5] audummy matches 0..5 run title @s actionbar ["",{"text":"This door is locked. ","color":"red"},{"score":{"name":"@e[tag=ldele3,limit=1]","objective":"audummy"},"bold":true,"color":"gold"},{"text":"/5","bold":true,"color":"gold"}]
execute as @s at @s if score @e[tag=ldlab1,limit=1,sort=nearest,distance=..2.5] audummy matches 0..5 run title @s actionbar ["",{"text":"This door is locked. ","color":"red"},{"score":{"name":"@e[tag=ldlab1,limit=1]","objective":"audummy"},"bold":true,"color":"gold"},{"text":"/5","bold":true,"color":"gold"}]
execute as @s at @s if score @e[tag=ldlab2,limit=1,sort=nearest,distance=..2.5] audummy matches 0..5 run title @s actionbar ["",{"text":"This door is locked. ","color":"red"},{"score":{"name":"@e[tag=ldlab2,limit=1]","objective":"audummy"},"bold":true,"color":"gold"},{"text":"/5","bold":true,"color":"gold"}]
execute as @s at @s if score @e[tag=ldcomms,limit=1,sort=nearest,distance=..2.5] audummy matches 0..5 run title @s actionbar ["",{"text":"This door is locked. ","color":"red"},{"score":{"name":"@e[tag=ldcomms,limit=1]","objective":"audummy"},"bold":true,"color":"gold"},{"text":"/5","bold":true,"color":"gold"}]
execute as @s at @s if score @e[tag=ldstor,limit=1,sort=nearest,distance=..2.5] audummy matches 0..5 run title @s actionbar ["",{"text":"This door is locked. ","color":"red"},{"score":{"name":"@e[tag=ldstor,limit=1]","objective":"audummy"},"bold":true,"color":"gold"},{"text":"/5","bold":true,"color":"gold"}]
execute as @s at @s if score @e[tag=ldwep,limit=1,sort=nearest,distance=..2.5] audummy matches 0..5 run title @s actionbar ["",{"text":"This door is locked. ","color":"red"},{"score":{"name":"@e[tag=ldwep,limit=1]","objective":"audummy"},"bold":true,"color":"gold"},{"text":"/5","bold":true,"color":"gold"}]

execute as @s at @s if score reactorcheck audummy matches 1 if entity @e[tag=reactormeltdown,limit=1,sort=nearest,distance=..1.5] run title @s actionbar ["",{"text":"Reactor Normal.","color":"aqua"}]
execute as @s at @s if score reactorcheck audummy matches 0 if score @e[tag=reactormeltdown,limit=1,sort=nearest,distance=..1.5] audummy matches 0 run title @s actionbar ["",{"text":"Hold to stop Reactor Meltdown.","color":"red"}]

execute as @s at @s if score reactorcheckm audummy matches 1 if entity @e[tag=reactormeltdownm,limit=1,sort=nearest,distance=..1.5] run title @s actionbar ["",{"text":"Reactor Normal.","color":"aqua"}]
execute as @s at @s if score reactorcheckm audummy matches 0 if score @e[tag=reactormeltdownm,limit=1,sort=nearest,distance=..1.5] audummy matches 0 run title @s actionbar ["",{"text":"Hold to stop Reactor Meltdown.","color":"red"}]

execute as @s at @s if score seismiccheck audummy matches 1 if entity @e[tag=seismicmeltdown,limit=1,sort=nearest,distance=..1.5] run title @s actionbar ["",{"text":"Seismic Stabilizers Normal.","color":"aqua"}]
execute as @s at @s if score seismiccheck audummy matches 0 if score @e[tag=seismicmeltdown,limit=1,sort=nearest,distance=..1.5] audummy matches 0 run title @s actionbar ["",{"text":"Hold to stop Sesismic Stabilizers Meltdown.","color":"red"}]

execute as @s at @s if entity @e[tag=auvending,limit=1,sort=nearest,distance=..2] if score @s auvending matches 1.. run title @s actionbar ["",{"text":"Vending Machine available in ","color":"dark_green"},{"score":{"name":"@s","objective":"auvending"},"color":"green"},{"text":" seconds.","color":"dark_green"}]
execute as @s at @s if entity @e[tag=auvending,limit=1,sort=nearest,distance=..2] if score @s auvending matches 0 run title @s actionbar ["",{"text":"Vending Machine available. Have a drink!","color":"dark_green"}]

execute as @s at @s if entity @e[tag=auvitals,distance=..2.5,limit=1,sort=nearest] run title @s actionbar ["",{"text":"ALIVE: ","color":"green"},{"selector":"@a[tag=amongusplayer,tag=!aughost]","bold":true,"color":"green"},{"text":" DEAD: ","color":"dark_red"},{"selector":"@a[tag=aufreshkill]","bold":true,"color":"dark_red"},{"text":" D/C: ","color":"gray"},{"selector":"@a[tag=aughost,tag=!aufreshkill]","bold":true,"color":"gray"}]